In [1]:
import yfinance as yf

In [2]:
sp500 = yf.download("^GSPC", start="2016-01-01", end="2026-01-01")
sp500.to_csv("sp500.csv")

/tmp/ipykernel_16223/3205265358.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sp500 = yf.download("^GSPC", start="2016-01-01", end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

In [3]:
stoxx = yf.download("^STOXX", start="2016-01-01", end="2026-01-01")
stoxx.to_csv("stoxx600.csv")

/tmp/ipykernel_16223/1846886321.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stoxx = yf.download("^STOXX", start="2016-01-01", end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

In [20]:
ShanghaiComp = yf.download("000001.SS", start="2016-01-01", end="2026-01-01")
ShanghaiComp.to_csv("ShanghaiComp.csv")

/tmp/ipykernel_16223/3693072570.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  ShanghaiComp = yf.download("000001.SS", start="2016-01-01", end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

In [5]:
import pandas as pd

In [6]:
SP500 = pd.read_csv("sp500.csv")

In [8]:
SP500 = SP500.iloc[2:].copy()
SP500.columns = ["Date", "Close", "High", "Low", "Open", "Volume"]
SP500.reset_index(drop=True, inplace=True)

SP500["Date"] = pd.to_datetime(SP500["Date"])
SP500 = SP500.astype({
    "Close": float,
    "High": float,
    "Low": float,
    "Open": float,
    "Volume": float
})

In [12]:
STOXX600 = pd.read_csv("stoxx600.csv")

In [15]:
STOXX600 = STOXX600.iloc[2:].copy()
STOXX600.columns = ["Date", "Close", "High", "Low", "Open", "Volume"]
STOXX600.reset_index(drop=True, inplace=True)

STOXX600["Date"] = pd.to_datetime(STOXX600["Date"])
STOXX600 = STOXX600.astype({
    "Close": float,
    "High": float,
    "Low": float,
    "Open": float,
    "Volume": float
})

In [23]:
ShanghaiComp = pd.read_csv("ShanghaiComp.csv")

In [24]:
ShanghaiComp = ShanghaiComp.iloc[2:].copy()
ShanghaiComp.columns = ["Date", "Close", "High", "Low", "Open", "Volume"]
ShanghaiComp.reset_index(drop=True, inplace=True)

ShanghaiComp["Date"] = pd.to_datetime(ShanghaiComp["Date"])
ShanghaiComp = ShanghaiComp.astype({
    "Close": float,
    "High": float,
    "Low": float,
    "Open": float,
    "Volume": float
})

In [11]:
SP500.describe()

,Date,Close,High,Low,Open,Volume
count,2514,2514.000000,2514.000000,2514.000000,2514.000000,2.514000e+03
mean,2020-12-30 09:28:46.968973568,3770.420754,3789.841542,3748.132206,3769.783358,4.151839e+09
min,2016-01-04 00:00:00,1829.079956,1847.000000,1810.099976,1833.400024,0.000000e+00
25%,2018-07-02 06:00:00,2711.787476,2729.302551,2697.327454,2712.830078,3.500355e+09
50%,2020-12-29 12:00:00,3676.395020,3705.280029,3645.855103,3683.665039,3.922175e+09
75%,2023-06-29 18:00:00,4514.057373,4532.042358,4494.827637,4512.690063,4.598322e+09
max,2025-12-31 00:00:00,6932.049805,6945.770020,6921.600098,6936.020020,9.976520e+09
std,NaN,1292.637990,1298.569769,1285.870346,1292.474148,1.028491e+09

In [25]:
STOXX600.describe()

,Date,Close,High,Low,Open,Volume
count,2513,2513.000000,2513.000000,2513.000000,2513.000000,2.513000e+03
mean,2020-12-29 09:15:15.399920384,424.647843,426.723283,422.390255,424.575607,2.147798e+08
min,2016-01-04 00:00:00,279.660004,288.220001,268.570007,277.510010,0.000000e+00
25%,2018-07-02 00:00:00,374.329987,376.089996,372.799988,374.440002,1.732141e+08
50%,2021-01-05 00:00:00,407.869995,410.390015,405.670013,408.559998,2.014763e+08
75%,2023-06-28 00:00:00,467.350006,469.109985,464.850006,467.140015,2.383166e+08
max,2025-12-30 00:00:00,592.780029,593.419983,588.780029,588.859985,1.109144e+09
std,NaN,66.227174,66.149290,66.248491,66.155606,7.678845e+07

In [26]:
ShanghaiComp.describe()

,Date,Close,High,Low,Open,Volume
count,2428,2428.000000,2428.000000,2428.000000,2428.000000,2.428000e+03
mean,2020-12-31 18:28:28.072487680,3181.896756,3199.316934,3160.208302,3179.433552,2.943317e+05
min,2016-01-04 00:00:00,2464.363037,2488.479004,2440.906982,2446.019043,1.000000e+02
25%,2018-07-01 06:00:00,2979.063965,2998.262207,2959.108704,2978.697327,1.826750e+05
50%,2020-12-29 12:00:00,3184.969482,3197.588013,3162.392944,3183.140503,2.711000e+05
75%,2023-07-04 06:00:00,3364.462402,3382.257996,3345.832031,3364.106995,3.618500e+05
max,2025-12-31 00:00:00,4029.500977,4034.079102,3994.770996,4023.876953,1.313500e+06
std,NaN,285.660677,285.385466,285.845569,285.815458,1.444735e+05